### ISSUE TITLE
i have this issue

### ISSUE THREAD

**Issue by kleber011** [cleitonleonel/redecanais#4]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kleber/.local/lib/python3.10/site-packages/redecanais/__main__.py", line 105, in <module>
    filmes = rede.films(URL_SERVER, category=parameters)
  File "/home/kleber/.local/lib/python3.10/site-packages/redecanais/redecanais.py", line 227, in films
    categories_list = self.get_links_categories(url, category)
  File "/home/kleber/.local/lib/python3.10/site-packages/redecanais/redecanais.py", line 214, in get_links_categories
    info_category = self.categories(url, category['category'].capitalize() + ' ')[0]
  File "/home/kleber/.local/lib/python3.10/site-packages/redecanais/redecanais.py", line 318, in categories
    tags = soup.find_all('li', {'class': 'dropdown-submenu'})[0]
IndexError: list index out of range

**Comment by kleber011** [comment]
To solve the issue, you need to investigate why the list returned by soup.find_all('li', {'class': 'dropdown-submenu'}) is empty. This means that the script couldn't find any <li> tags with the class "dropdown-submenu" in the HTML source.

Here are a few steps you can take to troubleshoot and resolve the problem:

Verify the HTML structure: Check if the structure of the webpage you're trying to scrape has changed. Inspect the HTML source manually or use developer tools in your web browser to ensure that the expected elements with the "dropdown-submenu" class are present. Make sure the website hasn't undergone any updates that might have affected the class names or overall structure.

Update the scraping logic: If the HTML structure has changed, you'll need to update your code accordingly. Review the documentation or source code of the website to understand any modifications or new classes that might have been introduced. Adjust the BeautifulSoup selectors to target the correct elements based on the updated structure.

Handle cases with no matching elements: It's possible that there are scenarios where the expected elements are not present on the page. In such cases, you should handle this gracefully in your code to avoid errors. Before accessing the first element of the list, check if the list is empty to prevent the "IndexError." You can use an if statement or try-except block to handle this situation and provide appropriate feedback or take alternative actions.

Here's an example of how you can modify your code to handle the issue:

python
Copy code
tags = soup.find_all('li', {'class': 'dropdown-submenu'})
if tags:
    info_category = self.categories(url, category['category'].capitalize() + ' ')[0]
    # Continue with the rest of your code
else:
    # Handle the case where no matching elements are found
    print("No elements with class 'dropdown-submenu' found.")
    # Take appropriate actions or raise an exception if needed
By implementing these steps, you should be able to identify the cause of the issue and update your code accordingly to handle the situation when the expected elements are not found.

**Comment by cleitonleonel** [comment]
> Para resolver o problema, você precisa investigar porque a lista retornada por soup.find_all('li', {'class': 'dropdown-submenu'}) está vazia. Isso significa que o script não encontrou nenhum
> 
> * tags com a classe "submenu suspenso" no código-fonte HTML.
>   Aqui estão algumas etapas que você pode seguir para solucionar problemas e resolver o problema:
>   Verifique a estrutura HTML: verifique se a estrutura da página da Web que você está tentando copiar foi alterada. Inspecione a fonte HTML manualmente ou use as ferramentas do desenvolvedor em seu navegador da Web para garantir que os elementos esperados com a classe "submenu suspenso" estejam presentes. Certifique-se de que o site não sofreu nenhuma atualização que possa ter afetado os nomes das classes ou a estrutura geral.
>   Atualize a lógica de extração: se a estrutura HTML foi alterada, você precisará atualizar seu código de acordo. Revise a documentação ou o código-fonte do site para entender quaisquer modificações ou novas classes que possam ter sido introduzidas. Ajuste os seletores BeautifulSoup para direcionar os elementos corretos com base na estrutura atualizada.
>   Lidar com casos sem elementos correspondentes: é possível que existam cenários em que os elementos esperados não estejam presentes na página. Nesses casos, você deve lidar com isso normalmente em seu código para evitar erros. Antes de acessar o primeiro elemento da lista, verifique se a lista está vazia para evitar o "IndexError". Você pode usar uma instrução if ou bloco try-except para lidar com essa situação e fornecer feedback apropriado ou tomar ações alternativas.
>   Aqui está um exemplo de como você pode modificar seu código para lidar com o problema:
>   python 
>   Copiar 
>   tags de código = soup.find_all('li', {'class': 'submenu suspenso'}) 
>   if tags: 
>   info_category = self.categories(url, category['category'].capitalize() + ' ') [0] 
>   # Continue com o resto do seu código 
>   else: 
>   # Manipule o caso em que nenhum elemento correspondente for encontrado 
>   print("Nenhum elemento com a classe 'dropdown-submenu' encontrado.") 
>   # Tome as ações apropriadas ou gere uma exceção, se necessário 
>   By implementando essas etapas, você deve ser capaz de identificar a causa do problema e atualizar seu código de acordo para lidar com a situação quando os elementos esperados não forem encontrados.

GPT dá uma força né...
